# TODO:
# * drop 3.0.5 after acme.sh
# * drop git

FROM alpine:3.17
LABEL maintainer="Will <coderdreamer@gmail.com>"

ARG PODTMP="/tmp/pod"

RUN apk add --update --no-cache \
        nginx \
        openssl \
        git \
        curl \
        # Needed by acme.sh
        # wget doen't work for acme.sh, but curl does.
        # Guessing it is a bug.

 && mkdir "$PODTMP" \
 && wget \
        "https://codeload.github.com/acmesh-official/acme.sh/tar.gz/refs/tags/3.0.5" \
        -O "${PODTMP}/acme.sh.tar.gz" \

# Function to retrieve download URL.
 && github_url() { \
        wget -q -O - "https://api.github.com/repos/${1}/releases/tags/${2}" \
        | grep "browser_download_url" \
        | grep "$3" \
        | head -n 1 \
        | cut -d `printf "\x22"` -f 4 \
        ; \
    } \
 && github_download() { \
        url=$(github_url "$1" "$2" "$4") \
        && echo "Downloading ${1}@${2} (arch ${4}) from ${url} ..." \
        && wget "$url" -O "$3" \
         ; \
    } \
 && github_download "mikefarah/yq" "v4.33.2" "${PODTMP}/yq" "linux_amd64" \
 && github_download "xtls/xray-core" "v1.7.5" "${PODTMP}/xray.zip" "linux-64" \
  ;

COPY \
    "./entrypoint.sh" \
    "$PODTMP"

ARG YQ_FILE="/usr/local/bin/yq"
ARG XRAY_FILE="/usr/local/bin/xray"
ARG XRAY_DATA_DIR="/usr/local/share/xray"
ARG XRAY_CFG_DIR="/etc/xray"
ARG XRAY_EXT_CFG_DIR="/etc/xray/ext"
ARG ACME_EXE="/usr/local/bin/acme.sh"
ARG ACME_CRT_DIR="/var/raycan/acmesh/cert"
ARG ACME_HOME_DIR="/usr/local/bin/acmesh"
ARG ACME_CFG_DIR="/etc/acmesh"
ARG ENTRYPOINT_FILE="/usr/local/bin/entrypoint"

# Entrypoint
RUN mv "${PODTMP}/entrypoint.sh" "$ENTRYPOINT_FILE" \
 && chmod +x "$ENTRYPOINT_FILE" \
# yq
 && mv "${PODTMP}/yq" "$YQ_FILE" \
 && chmod +x "$YQ_FILE" \
# XRay
 && unzip "${PODTMP}/xray.zip" -d "${PODTMP}/xray" \
 && mv "${PODTMP}/xray/xray" "$XRAY_FILE" \
 && mkdir -p "$XRAY_DATA_DIR" \
 && mv "${PODTMP}/xray/geosite.dat" "${XRAY_DATA_DIR}/geosite.dat" \
 && mv "${PODTMP}/xray/geoip.dat" "${XRAY_DATA_DIR}/geoip.dat" \
 && chmod +x "$XRAY_FILE" \
 && rm "${PODTMP}/xray.zip" \
 && rm -r "${PODTMP}/xray" \
# acmesh
 && tar -zxf "${PODTMP}/acme.sh.tar.gz" --directory "${PODTMP}" \
 && cd "${PODTMP}/acme.sh-3.0.5" \
 && "./acme.sh" --install  \
        --home "$ACME_HOME_DIR" \
        --config-home "$ACME_CFG_DIR" \
        --cert-home "$ACME_CRT_DIR" \
 && cd / \
 && rm -rf "${PODTMP}/acme.sh-3.0.5" \
 && echo $'#!/bin/bash\n/usr/local/bin/acmesh/acme.sh "$@"' > "$ACME_EXE" \
 && chmod +x "$ACME_EXE" \

# clean up
 && rm -r "$PODTMP" \
  ;

ENTRYPOINT ["entrypoint"]
