inbounds:
- tag: xtls
  port: 443
  protocol: vless
  streamSettings:
    network: tcp
    security: xtls
    xtlsSettings:
      allowInsecure: false
      minVersion: "1.2"
      alpn:
      - http/1.1
      certificates:
      - certificateFile: /var/xray/crt/cert.pem
        keyFile: /var/xray/crt/key.pem
  settings:
    decryption: none
    fallbacks:
    - dest: 80
outbounds:
- tag: direct
  protocol: freedom
- tag: block
  protocol: blackhole
